### ISSUE TITLE
Fail to run zippy!

### ISSUE THREAD

**Issue by KooLi2015** [qunaibit/zippy-mirror#1]
After downloaded the latest zippy code and successfully built it via mx according to README.md, it always fail to run with the following commands:
mx python scriptfile.py
mx unittest python.test

The error is like below:
[thread:6] scope: JVMCI CompilerThread1
  [thread:6] scope: JVMCI CompilerThread1.HotSpotGraalCompiler
    [thread:6] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling
      [thread:6] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.InterceptException
      Exception occurred in scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.InterceptException
[thread:5] scope: JVMCI CompilerThread0
  [thread:5] scope: JVMCI CompilerThread0.HotSpotGraalCompiler
    [thread:5] scope: JVMCI CompilerThread0.HotSpotGraalCompiler.Compiling
      [thread:5] scope: JVMCI CompilerThread0.HotSpotGraalCompiler.Compiling.InterceptException
      Exception occurred in scope: JVMCI CompilerThread0.HotSpotGraalCompiler.Compiling.InterceptException
      Context obj java.lang.AssertionError
      Context obj DebugDumpScope[29]
      Context obj java.lang.AssertionError: a value is already registered for class java.lang.Object.clone(java.lang.Object)
      Context obj DebugDumpScope[16]
      Context obj HotSpotMethod<String.indexOf(int, int)>
      Context obj HotSpotMethod<String.charAt(int)>
java.lang.AssertionError
	at com.oracle.graal.hotspot.meta.HotSpotGraphBuilderPlugins.registerCRC32Plugins(HotSpotGraphBuilderPlugins.java:432)
	at com.oracle.graal.hotspot.meta.HotSpotGraphBuilderPlugins.access$900(HotSpotGraphBuilderPlugins.java:102)
	at com.oracle.graal.hotspot.meta.HotSpotGraphBuilderPlugins$1.run(HotSpotGraphBuilderPlugins.java:143)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.flushDeferrables(InvocationPlugins.java:564)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.get(InvocationPlugins.java:550)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.lookupInvocation(InvocationPlugins.java:691)
	at com.oracle.graal.replacements.ReplacementsImpl.getSubstitutionMethod(ReplacementsImpl.java:221)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.getIntrinsicGraph(HotSpotGraalCompiler.java:154)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:112)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:213)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:92)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:336)
java.lang.AssertionError: **a value is already registered for class** java.lang.Object.clone(java.lang.Object)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins$ClassPlugins.register(InvocationPlugins.java:507)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.put(InvocationPlugins.java:536)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.register(InvocationPlugins.java:644)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.access$000(InvocationPlugins.java:53)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins$Registration.register1(InvocationPlugins.java:195)
	at com.oracle.graal.hotspot.meta.HotSpotGraphBuilderPlugins.registerObjectPlugins(HotSpotGraphBuilderPlugins.java:157)
	at com.oracle.graal.hotspot.meta.HotSpotGraphBuilderPlugins.access$000(HotSpotGraphBuilderPlugins.java:102)
	at com.oracle.graal.hotspot.meta.HotSpotGraphBuilderPlugins$1.run(HotSpotGraphBuilderPlugins.java:134)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.flushDeferrables(InvocationPlugins.java:564)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.get(InvocationPlugins.java:550)
	at com.oracle.graal.nodes.graphbuilderconf.InvocationPlugins.lookupInvocation(InvocationPlugins.java:691)
	at com.oracle.graal.replacements.ReplacementsImpl.getSubstitutionMethod(ReplacementsImpl.java:221)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.getIntrinsicGraph(HotSpotGraalCompiler.java:154)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:112)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:213)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:92)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:336) 

    Does anyone meet the similar issue and how to overcome it?
    Thanks!

BRs,
Koo

**Comment by qunaibit** [comment]
are you using jdk 8u92?

**Comment by KooLi2015** [comment]
Yes, I use JDK 8u92.

**Comment by qunaibit** [comment]
Your issue seems to be related to your system.
I just updated ZipPy to the latest graal.
I have tested it on both OSX (10.10.5) and Linux (Ubuntu 12.04).
You can see the latest compile and run on travis-ci:
https://travis-ci.org/qunaibit/zippy-mirror

We haven't tested Windows.

if you are not using Windows, Could you please do a new clone in an empty folder and build it again.
